name: Lint with Black

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: "3.10"

      - name: Installing Python dependencies
        run: pip install black

      - uses: wearerequired/lint-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          black: true
          black_args: "--extend-exclude /VenvPythonGrafowe/"
          auto_fix: true